[build]
  command = "export PYTHONPATH=/opt/build/repo && python -m pip install -r requirements.txt && python manage.py collectstatic --noinput"
  publish = "staticfiles"

[build.environment]
  PYTHON_VERSION = "3.11"

[[redirects]]
  from = "/*"
  to = "/caraccessories_shop/asgi.py"
  status = 200
